### ISSUE TITLE
needs review. Might be bringing in too much complexity with union statement - but the use case needs to be stated.

### ISSUE THREAD

**Issue by Simo-climb** [AGLDWG/phs-ont#22]
needs review. Might be bringing in too much complexity with union statement - but the use case needs to be stated.

@F3RR3T  had a simple goal of using the "common name" preflabel. So the use of this with taxonID may be incorrect

_Originally posted by @Simo-climb in https://github.com/AGLDWG/phs-ont/pull/20#discussion_r618868581_

**Comment by F3RR3T** [comment]
I think this is no longer relevant?
