### ISSUE TITLE
properties/linkage of bycatch with the ability to become a sample needs to be supported

### ISSUE THREAD

**Issue by Simo-climb** [AGLDWG/phs-ont#24]
properties/linkage of bycatch with the ability to become a sample needs to be supported

_Originally posted by @Simo-climb in https://github.com/AGLDWG/phs-ont/pull/20#discussion_r618872861_

**Comment by F3RR3T** [comment]
see #25

**Comment by F3RR3T** [comment]
Now that we cleanly record specimens using `TaxonOccurrence`, we don't need the `Bycatch` concept at all.
