### ISSUE TITLE
the subclass of bycatch to stratum may not be correct. review why this was done. it will only be a subclass of taxon

### ISSUE THREAD

**Issue by Simo-climb** [AGLDWG/phs-ont#25]
the subclass of bycatch to stratum may not be correct. review why this was done. it will only be a subclass of taxon

_Originally posted by @Simo-climb in https://github.com/AGLDWG/phs-ont/pull/20#discussion_r618873711_

**Comment by F3RR3T** [comment]
We have done away with 'Bycatch'. The concept is covered by TaxonOccurrence; attributes of each identified specimen (whether it is a target pest or not) is recorded within this class.
