### ISSUE TITLE
document the purpose of ObservationMethodType class

### ISSUE THREAD

**Issue by Simo-climb** [AGLDWG/phs-ont#27]
document/clarify the use case for the class ObservationMethodType in phs.ttl

does this add superclassing of properties for trap types

@F3RR3T  and @Simo-climb  to ask @nicholascar

**Comment by F3RR3T** [comment]
`InspectionMethodType` (was `ObservationMethodType`) is the Concept Class to which all the inspection methods in the vocab belong.
See [vocabularies/inspectionMethodTypes.ttl](https://github.com/AGLDWG/phs-ont/blob/master/vocabularies/inspectionMethodTypes.ttl).
