### ISSUE TITLE
ammend capture method types to "inspection method"

### ISSUE THREAD

**Issue by Simo-climb** [AGLDWG/phs-ont#28]
https://github.com/AGLDWG/phs-ont/blob/580721d39a103ab630bc6d4636ee461ddfff09e2/vocabularies/capturingMethodTypes.ttl#L22

as per discussions with @F3RR3T change from capture method to inspection to cater for the more general case of "looking" for a pest and not finding one, vs "capture" which implies a positive capture

**Comment by F3RR3T** [comment]
See  #15
