### ISSUE TITLE
Enable syntax colouring in ttl files

### ISSUE THREAD

**Issue by F3RR3T** [AGLDWG/phs-ont#29]
A trivial problem (which I have already fixed tbh).
But if I say `fixes #29` in the commit comment, then this should autoclosed.
Let's find out!

**Comment by F3RR3T** [comment]
Note that if protege writes a ttl file, it nukes the '#' comment on line one, as well as any other 'text file' comments.
Not a great problem. My workflow is to view the ontology in Protege and edit in vim. Each time I save the file, Protege asks to reload it. The 'ttl' tab shows any errors, if they occur. useful for catching syntax errors such as no ; at the end of a line.

**Comment by dr-shorthair** [comment]
VScode does syntax highlighting based on the file suffix (.ttl) (I use the Stardog RDF Grammars extension).
