### ISSUE TITLE
Merge / rename phs-protege.ttl back to phs.ttl

### ISSUE THREAD

**Issue by F3RR3T** [AGLDWG/phs-ont#35]
A new file called `phs-protege.ttl` was copied from `phs.ttl` and heavily edited.

It would be better to rename the new file back to `phs.ttl` but I'm not sure how to do this in git.
@Simo-climb  Would it be:
    
    $ git rm phs.ttl
    $ git mv phs-protege.ttl phs.ttl
    $ git commit -am 'revert back to phs.ttl'

?

**Comment by dr-shorthair** [comment]
Git-life is easier if you use a graphical client, like Sourcetree or Github desktop ;-)

**Comment by F3RR3T** [comment]
Beware the siren song of the GUI.
