### ISSUE TITLE
Errors in ObservationLocation

### ISSUE THREAD

**Issue by F3RR3T** [AGLDWG/phs-ont#36]
I have created a class:

        :ObservationLocation rdf:type owl:Class  ;
                     rdfs:subClassOf  sosa:FeatureOfInterest ;
                     rdfs:subClassOf dwc:Location,
                                      [ rdf:type owl:Restriction ;
                                        owl:onProperty dcterms:type ;
                                        owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
                                        owl:onProperty dwc:decimalLatitude
                                      ], 
                                      [ rdf:type owl:Restriction ;
                                        owl:onProperty dcterms:type ;
                                        owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
                                        owl:onProperty dwc:decimalLongitude
                                      ], 
                                      [ rdf:type owl:Restriction ;
                                        owl:onProperty dcterms:type ;
                                        owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
                                        owl:onProperty dwc:geodeticDatum
                                      ], 
                                      [ rdf:type owl:Restriction ;
                                        owl:onProperty dcterms:type ;
                                        owl:qualifiedCardinality "0"^^xsd:nonNegativeInteger ;
                                        owl:onProperty dwc:coordinateUncertaintyInMeters
                                      ]; 
        
                     sosa:isFeatureOfInterestOf :SurveillanceEvent ;
                      skos:definition "The point location at which a surveillance event occured."@en ;
                      rdfs:comment "x"@en ;
                      skos:prefLabel "Observation Location"@en .
  
This is meant to be a container for latitude and longitude, as well as datum and accuracy.
Protege is reporting these restrictions as errors.

Could you review and suggest corrections?

**Comment by dr-shorthair** [comment]
Protege doesn't like cardinality constraints

**Comment by F3RR3T** [comment]
These errors should resolve once the `dwc:` terms are imported or aligned.
