### ISSUE TITLE
refactor all vocab class prefixes from blank colon to declared prefix in each file

### ISSUE THREAD

**Issue by Simo-climb** [AGLDWG/phs-ont#38]
for example 

https://github.com/AGLDWG/phs-ont/blob/f33be6d2ca56e3a0b637dfd230a69e2c42004052/vocabularies/effortUnitTypes.ttl#L36

**Comment by F3RR3T** [comment]
I think Nick's treatment/validation of the vocabs renders this ticket obsolete.
