### ISSUE TITLE
version IRI - link is broken

### ISSUE THREAD

**Issue by F3RR3T** [AGLDWG/phs-ont#46]
in phs.ttl: `owl:versionIRI <https://linked.data.gov.au/def/phs/0.2.1> ;`

But it points `https://raw.githubusercontent.com/AGLDWG/phs-ont/master/phs.html/0.2.1` which is a 404.

How should this be configured?

**Comment by nicholascar** [comment]
I've created a Git 0.2.1 release and pegged the version URI <https://linked.data.gov.au/def/phs/0.2.1> at the PHS HTML file in this release. This is also the current `master` branch commit, so this release and the un-versioned URI of <https://linked.data.gov.au/def/phs> currently point to the same file. We can update the version and release as needed and the version PID pattern will hold.
