### ISSUE TITLE
TargetPest as subclass of sosa:FeatureOfInterest

### ISSUE THREAD

**Issue by F3RR3T** [AGLDWG/phs-ont#53]
@Simo-climb is arranging a meeting to discuss/review the ontology as it stands, before we stop work on it for now.

I've modelled `phs:TargetPest` as a subclass of `sosa:FeatureOfInterest` .
(Formerly called `phs:TargetPestGroup` but "Group" just added syllables without adding meaning.)

From (https://www.w3.org/TR/vocab-ssn/#SOSAFeatureOfInterest):

> _Feature Of Interest_ - The thing whose property is being estimated or calculated in the course of an Observation to arrive at a Result...

There was some discussion as to whether this class is really an `sosa:ObservedProperty`. Let's work this out at our meeting. See also (upcoming) issue on what is modelled and what is not.

**Comment by dr-shorthair** [comment]
I think I would bind the `TargetPest` into the observed property. 
i.e. make the ObservableProperty `TargetPestOccurrence`.

**Comment by F3RR3T** [comment]
https://www.w3.org/TR/vocab-ssn-ext/#oboe
