### ISSUE TITLE
what is the policy of subclassing as owl:Thing for general top level owl:Classes

### ISSUE THREAD

**Issue by Simo-climb** [AGLDWG/phs-ont#60]
Likely a convention issue mixed with presentation issues.

While running conversions of owl to shacl shapes, the top braid composer tool has added inferencing of subclassing of owl:Thing for any owl:Classes that are not declared as a child of a named class.

I know this makes a difference in tools which present the ontologies to users in interfaces, but it likely makes no material difference to programmatical based validation. I assume any UX will do a similar inferencing on the fly anyway ?

Shall I keep instantiate the added subclassing or remove ? @nicholascar

**Comment by nicholascar** [comment]
Definitely no need to add `owl:Thing` to anything in the ontology or the vocabs. If TBC/EDG needs `owl:Thing` then sure, it can infer it.
